[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "k8s.io/kops"
  revision = "244d88829016e95bca916c5ba1f080e64541fcac"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.13"
 
[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/kubernetes"
  branch = "release-1.13"

[[override]]
  name = "github.com/coreos/etcd"
  revision = "6543273666cb9832edc2cc1d50f8e647d3575828"

[[override]]
  name = "go.etcd.io/etcd"
  revision = "6543273666cb9832edc2cc1d50f8e647d3575828"

[[override]]
  name = "github.com/docker/engine-api"
  revision = "dea108d3aa0c67d7162a3fd8aa65f38a430019fd"

[[override]]
  name = "github.com/ugorji/go"
  revision = "2dc34c0b87808deb8e2c69e1625db4c14e5d0d4a"
